version: "3.7"

secrets:
  CF_API_EMAIL:
    file: ./secrets/CF_API_EMAIL
  CF_API_KEY:
    file: ./secrets/CF_API_KEY
  TRAEFIK_SSL_CERT:
    file: ./secrets/traefik.crt
  TRAEFIK_SSL_KEY:
    file: ./secrets/traefik.key

networks:
  traefik-servicenet:
    name: traefik-servicenet
    driver: bridge
  traefik-docker-proxy:
    name: traefik-docker-proxy
    driver: bridge
  authentik-servicenet:
    name: authentik-servicenet
    driver: bridge
  ghost-servicenet:
    name: ghost-servicenet
    driver: bridge
  cloudflare-tunnel:
    name: cloudflare-tunnel
    driver: bridge

include:
  - services/authentik.yml
  - services/error-pages.yml
  - services/ghost.yml
  - services/traefik.yml
  - services/gitlab.yml
  - services/cloudflared.yml
