version: "3.7"

services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    networks:
      - cloudflare-tunnel
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
