version: "3.7"

services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.${DOMAIN}'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        registry_nginx['enable'] = true
        registry_nginx['listen_https'] = false
        registry_nginx['listen_port'] = '5005'
        registry_external_url 'https://registry.${DOMAIN}'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'
    labels:
      - "traefik.enable=true"
      # 1. create gitlab router
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.${DOMAIN}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.routers.gitlab.tls.certresolver=cloudflare"
      - "traefik.http.routers.gitlab.middlewares=chain-no-auth@file"
      - "traefik.http.routers.gitlab.service=gitlab"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      # 2. create registry router
      - "traefik.http.routers.gitlab-registry.rule=Host(`registry.${DOMAIN}`)"
      - "traefik.http.routers.gitlab-registry.entrypoints=websecure"
      - "traefik.http.routers.gitlab-registry.tls=true"
      - "traefik.http.routers.gitlab-registry.tls.certresolver=cloudflare"
      - "traefik.http.routers.gitlab-registry.middlewares=chain-no-auth@file"
      - "traefik.http.routers.gitlab-registry.service=gitlab-registry"
      - "traefik.http.services.gitlab-registry.loadbalancer.server.port=5005"
    networks:
      - traefik-servicenet

volumes:
  gitlab_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=${NFS_HOST:?nfs host must be set},nfsvers=4,rw
      device: ":/mnt/data-pool/docker01/gitlab/data"
  gitlab_logs:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=${NFS_HOST:?nfs host must be set},nfsvers=4,rw
      device: ":/mnt/data-pool/docker01/gitlab/logs"
  gitlab_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=${NFS_HOST:?nfs host must be set},nfsvers=4,rw
      device: ":/mnt/data-pool/docker01/gitlab/config"
